# Generated by Django 4.0 on 2023-05-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='telefono',
            field=models.CharField(default=555555, max_length=200),
            preserve_default=False,
        ),
    ]
