# Generated by Django 4.0 on 2023-05-15 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='cakes/')),
                ('filling', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='CakeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='base/')),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CakeLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='layers/')),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CakeMeringue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='meringues/')),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CakeSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='samples/')),
                ('filling', models.TextField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuyakake.cakebase')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='yuyakake.cake')),
                ('layers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuyakake.cakelayer')),
                ('meringue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuyakake.cakemeringue')),
            ],
        ),
        migrations.CreateModel(
            name='CakeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='sizes/')),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=200)),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('P', 'Pendiente'), ('E', 'En preparación'), ('L', 'Listo para recoger'), ('C', 'Completado'), ('X', 'Cancelado')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuyakake.cake')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='yuyakake.order')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuyakake.cakesample')),
            ],
        ),
        migrations.AddField(
            model_name='cakesample',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuyakake.cakesize'),
        ),
        migrations.CreateModel(
            name='CakeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('review', models.TextField(blank=True, null=True)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuyakake.cake')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='cake',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuyakake.cakebase'),
        ),
        migrations.AddField(
            model_name='cake',
            name='layers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuyakake.cakelayer'),
        ),
        migrations.AddField(
            model_name='cake',
            name='meringue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuyakake.cakemeringue'),
        ),
        migrations.AddField(
            model_name='cake',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuyakake.cakesize'),
        ),
    ]
